keyMirror = require('react/lib/keyMirror')

module.exports =
  ActionTypes: keyMirror
    WR_GDRIVE_LOAD_FILES_SUCCESS: null
    WR_GDRIVE_API_ERROR: null

    WR_GDRIVE_LOAD_GOOGLEINFO_SUCCESS: null
    WR_GDRIVE_LOAD_GOOGLEINFO_START: null

    WR_GDRIVE_SET_EDITING: null

    WR_GDRIVE_SAVEFILE_START: null

    WR_GDRIVE_SAVEFILE_SUCCESS: null

    WR_GDRIVE_DELETE_ROW_START: null
    WR_GDRIVE_DELETE_ROW_DELETE: null
    WR_GDRIVE_LOAD_ACCOUNT_SUCCESS: null
