language: node_js
node_js: "7"
branches:
  only:
    - master
before_script:
  - git --version
  - git describe --tags
  - export KBC_REVISION=`git describe --tags`
script:
 - yarn test
 - yarn build
sudo: false
cache:
  yarn: true
deploy:
- provider: s3
  access_key_id: AKIAJPIXG5FWMBKORQZA
  secret_access_key:
    secure: YnoCx0iURkQ9H9FLamLh8Hr7n2kosPURs7kYeVc5/AFeaprGSfRjOxP2kkOls9esvNfK3mbMpDStFZc4/BSC5nGG+fOL5WQK8r+YVGzlFXfBNu2FgSC/uGd4QeCOgvEDo7k06320LJrJBqQsUQ5484J7TnDq5AzKljDA77f2+Cc=
  bucket: kbc-uis
  local-dir: dist
  upload-dir: kbc
  acl: public_read
  skip_cleanup: true
  cache_control: max-age=31536000
  detect_encoding: true
  on:
    repo: keboola/kbc-ui
after_deploy:
- echo $KBC_REVISION
- export BODY="{\"manifestUrl\":\"https://kbc-uis.s3.amazonaws.com/kbc/$KBC_REVISION/manifest.json\",\"activate\":true}"
- curl -H X-KBC-ManageApiToken:$KBC_ADMIN_TOKEN_DEVEL -d $BODY -H "Content-Type:application/json" https://martin-connection-devel.keboola.com/manage/ui-apps
- curl -H X-KBC-ManageApiToken:$KBC_ADMIN_TOKEN_PROD -d $BODY -H "Content-Type:application/json" https://connection.keboola.com/manage/ui-apps
- export BODY="{\"version\":\"$KBC_REVISION\"}"
- curl -H "Authorization:Bearer $SENTRY_TOKEN" -H 'Content-Type:application/json' -d $BODY -X POST https://app.getsentry.com/api/0/projects//keboola/keboola-connection-ui/releases/ \

notifications:
  slack:
    secure: QEH74o00ud7Q0TjKZ5yWzfHMZyq94KUYR/cWe+P0LbMocCbD25GzW/LnTpM+iJQjkDktR3+iZ53ycLOMbrGzFdPwUDIa98FRjv9nMIz0s1ZQv7/5/ydER7wppYT2ID/paIvUMkFQY0cXq0ZIOii66XwV21FPjVUHbOAxjwyWr+U=
