keyMirror = require('react/lib/keyMirror')

module.exports =


  ActionTypes: keyMirror(
    ORCHESTRATIONS_LOAD: null
    ORCHESTRATIONS_LOAD_SUCCESS: null
    ORCHESTRATIONS_LOAD_ERROR: null
    ORCHESTRATIONS_SET_FILTER: null

    ORCHESTRATION_JOBS_LOAD: null
    ORCHESTRATION_JOBS_LOAD_SUCCESS: null
    ORCHESTRATION_JOBS_LOAD_ERROR: null

    ORCHESTRATION_LOAD: null
    ORCHESTRATION_CREATE_SUCCESS: null

    ORCHESTRATION_DELETE_START: null
    ORCHESTRATION_DELETE_SUCCESS: null
    ORCHESTRATION_DELETE_ERROR: null

    ORCHESTRATION_LOAD_SUCCESS: null
    ORCHESTRATION_LOAD_ERROR: null

    ORCHESTRATION_ACTIVE_CHANGE_START: null
    ORCHESTRATION_ACTIVE_CHANGE_SUCCESS: null
    ORCHESTRATION_ACTIVE_CHANGE_ERROR: null

    ORCHESTRATION_DISABLE: null
    ORCHESTRATION_SET_TASKS: null

    ORCHESTRATION_JOB_LOAD: null
    ORCHESTRATION_JOB_LOAD_SUCCESS: null
    ORCHESTRATION_JOB_LOAD_ERROR: null
  )
