keyMirror = require('react/lib/keyMirror')

module.exports =
  ActionTypes: keyMirror(
    EX_GANAL_CONFIGURATION_LOAD_SUCCEES: null
    EX_GANAL_CHANGE_NEW_QUERY: null
    EX_GANAL_NEW_QUERY_RESET: null
    EX_GANAL_NEW_QUERY_CREATE_SUCCESS: null
    EX_GANAL_NEW_QUERY_CREATE_START: null
    EX_GANAL_CHANGE_QUERY: null
    EX_GANAL_QUERY_TOOGLE_EDITING: null
    EX_GANAL_QUERY_RESET: null
    EX_GANAL_QUERY_SAVE_SUCCESS: null
    EX_GANAL_QUERY_SAVE_START: null
    EX_GANAL_GENERATE_EXT_LINK_END: null
    EX_GANAL_GENERATE_EXT_LINK_START: null
    EX_GANAL_PROFILES_LOAD_SUCCESS: null
    EX_GANAL_SELECT_PROFILE: null
    EX_GANAL_DESELECT_PROFILE: null
    EX_GANAL_SELECT_PROFILE_CANCEL: null
    EX_GANAL_SELECT_PROFILE_SAVE: null
    EX_GANAL_OUTBUCKET_SAVE: null
    EX_GANAL_OUTBUCKET_SAVE_SUCCESS: null
    EX_GANAL_DELETE_QUERY: null
    EX_GANAL_DELETE_QUERY_SUCCESS: null
    EX_GANAL_SEND_LINK: null
    EX_GANAL_SEND_LINK_SUCCESS: null
    EX_GANAL_API_ERROR: null
  )
