keyMirror = require('react/lib/keyMirror')

module.exports =


  ActionTypes: keyMirror(
    TRANSFORMATION_BUCKETS_LOAD: null
    TRANSFORMATION_BUCKETS_LOAD_SUCCESS: null
    TRANSFORMATION_BUCKETS_LOAD_ERROR: null

    TRANSFORMATION_BUCKET_CREATE: null
    TRANSFORMATION_BUCKET_CREATE_SUCCESS: null
    TRANSFORMATION_BUCKET_CREATE_ERROR: null

    TRANSFORMATION_BUCKET_DELETE_START: null
    TRANSFORMATION_BUCKET_DELETE_SUCCESS: null
    TRANSFORMATION_BUCKET_DELETE_ERROR: null

    TRANSFORMATIONS_LOAD: null
    TRANSFORMATIONS_LOAD_SUCCESS: null
    TRANSFORMATIONS_LOAD_ERROR: null

    TRANSFORMATION_DELETE: null
    TRANSFORMATION_DELETE_SUCCESS: null
    TRANSFORMATION_DELETE_ERROR: null
  )
