keyMirror = require('react/lib/keyMirror')

module.exports =


  ActionTypes: keyMirror(
    TRANSFORMATION_BUCKETS_LOAD: null
    TRANSFORMATION_BUCKETS_LOAD_SUCCESS: null
    TRANSFORMATION_BUCKETS_LOAD_ERROR: null

    TRANSFORMATION_BUCKET_CREATE: null
    TRANSFORMATION_BUCKET_CREATE_SUCCESS: null
    TRANSFORMATION_BUCKET_CREATE_ERROR: null

    TRANSFORMATION_BUCKET_DELETE: null
    TRANSFORMATION_BUCKET_DELETE_SUCCESS: null
    TRANSFORMATION_BUCKET_DELETE_ERROR: null

    TRANSFORMATIONS_LOAD: null
    TRANSFORMATIONS_LOAD_SUCCESS: null
    TRANSFORMATIONS_LOAD_ERROR: null

    TRANSFORMATION_DELETE: null
    TRANSFORMATION_DELETE_SUCCESS: null
    TRANSFORMATION_DELETE_ERROR: null

    TRANSFORMATION_OVERVIEW_LOAD: null
    TRANSFORMATION_OVERVIEW_LOAD_SUCCESS: null
    TRANSFORMATION_OVERVIEW_LOAD_ERROR: null
    TRANSFORMATION_OVERVIEW_SHOW_DISABLED: null

    TRANSFORMATION_INPUT_MAPPING_OPEN_TOGGLE: null
    TRANSFORMATION_OUTPUT_MAPPING_OPEN_TOGGLE: null

    TRANSFORMATION_EDIT_START: null
    TRANSFORMATION_EDIT_CANCEL: null
    TRANSFORMATION_EDIT_SAVE_START: null
    TRANSFORMATION_EDIT_SAVE_SUCCESS: null
    TRANSFORMATION_EDIT_SAVE_ERROR: null
    TRANSFORMATION_EDIT_CHANGE: null

    TRANSFORMATION_EDIT_INPUT_MAPPING_OPEN_TOGGLE: null
    TRANSFORMATION_EDIT_INPUT_MAPPING_ADD: null
    TRANSFORMATION_EDIT_INPUT_MAPPING_DELETE: null

    TRANSFORMATION_EDIT_OUTPUT_MAPPING_OPEN_TOGGLE: null
    TRANSFORMATION_EDIT_OUTPUT_MAPPING_ADD: null
    TRANSFORMATION_EDIT_OUTPUT_MAPPING_DELETE: null

  )
