keyMirror = require('react/lib/keyMirror')

module.exports =
  ActionTypes: keyMirror(
    EX_GDRIVE_CONFIGURATION_LOAD_SUCCESS: null
    EX_GDRIVE_SHEET_EDIT_START: null
    EX_GDRIVE_SHEET_EDIT_CANCEL: null
    EX_GDRIVE_SHEET_EDIT_SAVE_START: null
    EX_GDRIVE_SHEET_EDIT_SAVE_END: null
    EX_GDRIVE_SHEET_ON_CHANGE: null
    EX_GDRIVE_SHEET_EDIT_VALIDATE: null
    EX_GDRIVE_SHEET_DELETE_START: null
    EX_GDRIVE_SHEET_DELETE_END: null
    EX_GDRIVE_FILES_LOAD_SUCCESS: null
    EX_GDRIVE_FILE_SHEETS_LOAD_SUCCESS: null
    EX_GDRIVE_FILE_SHEETS_LOAD_START: null
    EX_GDRIVE_SELECT_SHEET: null
    EX_GDRIVE_DESELECT_SHEET: null
    EX_GDRIVE_LOADING_MORE_SUCCESS: null
    EX_GDRIVE_LOADING_MORE_START: null
    EX_GDRIVE_SEARCH_QUERY_CHANGE: null
    EX_GDRIVE_SAVING_SHEETS_START: null
    EX_GDRIVE_SAVING_SHEETS_SUCCESS: null
    EX_GDRIVE_SAVING_SHEETS_CANCEL: null
  )
