keyMirror = require('react/lib/keyMirror')

module.exports =

  ActionTypes: keyMirror

    # Components
    COMPONENTS_SET_FILTER: null
    COMPONENTS_LOAD_SUCCESS: null

    # Installed components
    INSTALLED_COMPONENTS_LOAD: null
    INSTALLED_COMPONENTS_LOAD_SUCCESS: null
    INSTALLED_COMPONENTS_LOAD_ERROR: null

    INSTALLED_COMPONENTS_CONFIGURATION_EDIT_START: null
    INSTALLED_COMPONENTS_CONFIGURATION_EDIT_CANCEL: null
    INSTALLED_COMPONENTS_CONFIGURATION_EDIT_UPDATE: null

    INSTALLED_COMPONENTS_UPDATE_CONFIGURATION_START: null
    INSTALLED_COMPONENTS_UPDATE_CONFIGURATION_SUCCESS: null
    INSTALLED_COMPONENTS_UPDATE_CONFIGURATION_ERROR: null

    # New configurations
    COMPONENTS_NEW_CONFIGURATION_UPDATE: null
    COMPONENTS_NEW_CONFIGURATION_CANCEL: null
    COMPONENTS_NEW_CONFIGURATION_SAVE_START: null
    COMPONENTS_NEW_CONFIGURATION_SAVE_SUCCESS: null
    COMPONENTS_NEW_CONFIGURATION_SAVE_ERROR: null

  GoodDataWriterModes: keyMirror
    NEW: null
    EXISTING: null

  GoodDataWriterTokenTypes: keyMirror
    PRODUCTION: null
    DEVELOPER: null
    CUSTOM: null

