keyMirror = require('react/lib/keyMirror')

module.exports =

  ActionTypes: keyMirror(
    EX_DB_CONFIGURATION_LOAD_SUCCESS: null

    EX_DB_QUERY_EDIT_START: null
    EX_DB_QUERY_EDIT_CANCEL: null
    EX_DB_QUERY_EDIT_UPDATE: null

    EX_DB_QUERY_EDIT_SAVE_START: null
    EX_DB_QUERY_EDIT_SAVE_SUCCESS: null
    EX_DB_QUERY_EDIT_SAVE_ERROR: null

    EX_DB_QUERY_DELETE: null

    EX_DB_NEW_QUERY_UPDATE: null
    EX_DB_NEW_QUERY_RESET: null
    EX_DB_NEW_QUERY_CREATED: null

    EX_DB_CREDENTIALS_EDIT_START: null
    EX_DB_CREDENTIALS_EDIT_CANCEL: null
    EX_DB_CREDENTIALS_EDIT_UPDATE: null
    EX_DB_CREDENTIALS_EDIT_SAVE: null
  )
