keyMirror = require('react/lib/keyMirror')

module.exports =
  ActionTypes: keyMirror(
    CREDENTIALS_LOAD: null
    CREDENTIALS_LOAD_SUCCESS: null
    CREDENTIALS_LOAD_ERROR: null

    CREDENTIALS_CREATE: null
    CREDENTIALS_CREATE_SUCCESS: null
    CREDENTIALS_CREATE_ERROR: null

    CREDENTIALS_DROP: null
    CREDENTIALS_DROP_SUCCESS: null
    CREDENTIALS_DROP_ERROR: null

    CREDENTIALS_MYSQL_SANDBOX_LOAD: null
    CREDENTIALS_MYSQL_SANDBOX_LOAD_SUCCESS: null
    CREDENTIALS_MYSQL_SANDBOX_LOAD_ERROR: null

    CREDENTIALS_MYSQL_SANDBOX_CREATE: null
    CREDENTIALS_MYSQL_SANDBOX_CREATE_SUCCESS: null
    CREDENTIALS_MYSQL_SANDBOX_CREATE_ERROR: null

    CREDENTIALS_MYSQL_SANDBOX_DROP: null
    CREDENTIALS_MYSQL_SANDBOX_DROP_SUCCESS: null
    CREDENTIALS_MYSQL_SANDBOX_DROP_ERROR: null


  )
